version: '3'

services:
  
  web:
    image: web-security-study/web
    container_name: web-security-study-web
    build:
      context: "./web"
      dockerfile: "Dockerfile"
    ports:
      - "80:80"
    restart: always
    environment:
     - TZ=Asia/Tokyo
    volumes:
     - ./web/logs:/var/log
     - ../public:/var/www/html
     - ./web/config/php/php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: web-security-study/mysql
    container_name: web-security-study-mysql
    build:
      context: "./mysql"
      dockerfile: "Dockerfile"
    environment:
      MYSQL_DATABASE: web_security_study
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
     - "3306:3306"
    restart: always
    volumes:
      - db-store:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d

volumes:
  db-store:
